---
- hosts: all
  become: yes
  tasks:
  - name: Update 
    apt:
     update_cache: yes
  - name: install jdk
    apt:
     name: default-jdk
     state: present
  - name: cretae group
    group:
     name: tomcat
     state: present
  - name: create user
    user:
     name: tomcat
     shell: /bin/false
     groups: tomcat
     home: /opt/tomcat
  - name: download
    get_url:
      url: http://apachemirror.wuchna.com/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz
      dest: /tmp
      force_basic_auth: yes
  - name: create dir
    file:
     path: /opt/tomcat
     state: directory
  - name: Recursively change ownership of a directory
    file:
     path: /opt/tomcat
     state: directory
     recurse: yes
  - name: Change file ownership, group and permissions
    file:
     path: /opt/tomcat
     group: tomcat
  - name: Recursively change ownership of a directory
    file:
     path: /opt/tomcat/conf
     recurse: yes
  - name: read permisions
    file:
     path: /opt/tomcat/conf
     mode: g+r
  - name: execye permisions
    file:
     path: /opt/tomcat/conf
     mode: g+x
  - name: Change file ownership, group and permissions
    file:
     path: "{{ item }}"
     recurse: yes
    loop:
      - /opt/tomcatwebapps
      - /opt/tomcat/work
      - /opt/tomcattemp
      - /opt/tomcat/logs
  - name: Change file ownership, group and permissions
    file:
     path: "{{ item }}"
     owner: tomcat
    loop:
      - /opt/tomcat/webapps
      - /opt/tomcat/work
      - /opt/tomcat/temp
      - /opt/tomcat/logs
  - name: deamon reloaded
    systemd:
     state: restarted
     daemon_reload: yes
  - name: Make sure a service is running
    systemd:
     state: started
     name: tomcat